### PR TITLE
Update StageXL dep

### PR DESCRIPTION
**Pull request by mnordine**

### CODE REVIEW

**Comment by bp74** [comment]
Thanks! I assume ^1.0.0 did not work, right?

**Comment by mnordine** [comment]
Sorry Bernhard, it seems the first time I tried, pub used StageXL 1.0. I just went back and tried `pub upgrade` and it did indeed work.

**Comment by bp74** [comment]
Does this mean that ^1.0.0 was okay?

**Comment by mnordine** [comment]
Sorry, that's correct Bernhard. I think I created a StageXL template with WebStorm, and it defaults to 1.1.0, and I thought it was an issue with the dependency.

**Comment by bp74** [comment]
Okay no problem. I am planning to raise the dependencies for all StageXL libraries anyway some time after Dart 1.24 was released.

**Pull request merged**
